version: '3.8'

services:
  app:
    build:
      context: ./php
    container_name: laravel-app
    volumes:
      - ./src/games-aggregator-cms:/var/www/html
    networks:
      - laravel
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    entrypoint: |
      bash -c "
        # Set permissions for storage and cache directories
        chmod -R 775 /var/www/html/storage
        chmod -R 775 /var/www/html/bootstrap/cache
        chown -R www-data:www-data /var/www/html/storage
        chown -R www-data:www-data /var/www/html/bootstrap/cache

        # Run Laravel artisan commands
        php artisan key:generate

        # Start PHP-FPM
        exec php-fpm
      "


  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8000:80"
      # - "443:443"
    volumes:
      - ./src/games-aggregator-cms:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    command: --sql-mode="NO_ENGINE_SUBSTITUTION"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data:
